name: TheRock CI Linux

on:
  workflow_call:
    inputs:
      cmake_options:
        type: string
      project_to_test:
        type: string
      test_type:
        type: string

permissions:
  contents: read

jobs:
  therock-build-linux:
    name: Build
    runs-on: azure-linux-scale-rocm
    permissions:
      id-token: write
    container:
      image: ghcr.io/rocm/therock_build_manylinux_x86_64@sha256:2f3ebd0beb04c449fdb36933e54bdc69483b914fb9005594d3fc9444c206b54b
      options: -v /runner/config:/home/awsconfig/
    strategy:
      fail-fast: true
    env:
      CACHE_DIR: ${{ github.workspace }}/.container-cache
      CCACHE_CONFIGPATH: ${{ github.workspace }}/.ccache/ccache.conf
      AMDGPU_FAMILIES: "gfx94X-dcgpu"
      TEATIME_FORCE_INTERACTIVE: 0
      AWS_SHARED_CREDENTIALS_FILE: /home/awsconfig/credentials.ini
    steps:
      - name: "Checking out repository for rocm-libraries"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # We only want to build MIOpen HEAD against CK HEAD, not applicable for other projects
      - name: Checkout composable_kernel repository
        if: ${{ contains(inputs.project_to_test, 'miopen') }}
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          repository: "ROCm/composable_kernel"
          path: "composable_kernel"
        
      - name: Checkout TheRock repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          repository: "ROCm/TheRock"
          path: TheRock
          ref: 6ecc2af91fc8a4271a949005d7404bd13278c005 # 2025-10-23 commit

      - name: Install python deps
        run: |
          pip install -r TheRock/requirements.txt

      # safe.directory must be set before Runner health status
      - name: Adjust git config
        run: |
          git config --global --add safe.directory $PWD
          git config fetch.parallel 10

      - name: Setup ccache
        run: |
          ./TheRock/build_tools/setup_ccache.py \
            --config-preset "github-oss-presubmit" \
            --dir "$(dirname $CCACHE_CONFIGPATH)" \
            --local-path "$CACHE_DIR/ccache"

      - name: Runner health status
        run: |
          ./TheRock/build_tools/health_status.py

      - name: Pull DVC files for rocm-libraries # LOGNAME details here https://github.com/ROCm/rocm-libraries/pull/1617
        run: |
          if command -v dvc &> /dev/null; then
            echo "dvc detected"
          else
            echo "Warning, dvc not detected!"
          fi
          LOGNAME=github-runner dvc pull -v

      - name: Fetch sources
        timeout-minutes: 30
        run: |
          ./TheRock/build_tools/fetch_sources.py --jobs 12 --no-include-rocm-libraries --no-include-ml-frameworks

      - name: Patch rocm-libraries
        run: |
          git -c user.name="therockbot" -c "user.email=therockbot@amd.com" am --whitespace=nowarn ./TheRock/patches/amd-mainline/rocm-libraries/*.patch

      - name: Configure Projects
        env:
          amdgpu_families: ${{ env.AMDGPU_FAMILIES }}
          package_version: ADHOCBUILD
          extra_cmake_options: "-DTHEROCK_ROCM_LIBRARIES_SOURCE_DIR=../ ${{ inputs.cmake_options }}"
          BUILD_DIR: build
        run: |
          python3 TheRock/build_tools/github_actions/build_configure.py

      - name: Build therock-dist
        run: cmake --build TheRock/build --target therock-dist

      - name: Build therock-archives
        run: cmake --build TheRock/build --target therock-archives

      - name: Report
        if: ${{ !cancelled() }}
        run: |
          echo "Full SDK du:"
          echo "------------"
          du -h -d 1 TheRock/build/dist/rocm
          echo "Artifact Archives:"
          echo "------------------"
          ls -lh TheRock/build/artifacts/*.tar.xz
          echo "Artifacts:"
          echo "----------"
          du -h -d 1 TheRock/build/artifacts
          echo "CCache Stats:"
          echo "-------------"
          ccache -s -v
          tail -v -n +1 .ccache/compiler_check_cache/* > TheRock/build/logs/ccache_compiler_check_cache.log

      - name: Configure AWS Credentials for non-forked repos
        if: ${{ always() && !github.event.pull_request.head.repo.fork }}
        uses: aws-actions/configure-aws-credentials@a03048d87541d1d9fcf2ecf528a4a65ba9bd7838 # v5.0.0
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::692859939525:role/therock-artifacts-external

      - name: Post Build Upload
        if: always()
        run: |
          python3 TheRock/build_tools/github_actions/post_build_upload.py \
            --run-id ${{ github.run_id }} \
            --artifact-group ${{ env.AMDGPU_FAMILIES }} \
            --build-dir TheRock/build \
            --upload

  therock-test-linux:
    name: "Test"
    needs: [therock-build-linux]
    uses: ./.github/workflows/therock-test-packages.yml
    with:
      project_to_test: ${{ inputs.project_to_test }}
      amdgpu_families: "gfx94X-dcgpu"
      test_runs_on: "linux-mi325-1gpu-ossci-rocm"
      platform: "linux"
      test_type: ${{ inputs.test_type }}
