# Supported OS + ROCm combinations for continuous integration

matrix:
  # ubuntu 22.04
  - os-distro: "ubuntu"
    os-version: "22.04"
    rocm-version: "0.0"
  - os-distro: "ubuntu"
    os-version: "22.04"
    rocm-version: "6.3"
  - os-distro: "ubuntu"
    os-version: "22.04"
    rocm-version: "6.4"
  - os-distro: "ubuntu"
    os-version: "22.04"
    rocm-version: "7.0"
  # ubuntu 24.04
  - os-distro: "ubuntu"
    os-version: "24.04"
    rocm-version: "0.0"
  - os-distro: "ubuntu"
    os-version: "24.04"
    rocm-version: "6.3"
  - os-distro: "ubuntu"
    os-version: "24.04"
    rocm-version: "6.4"
  - os-distro: "ubuntu"
    os-version: "24.04"
    rocm-version: "7.0"
  # opensuse 15.5
  - os-distro: "opensuse"
    os-version: "15.5"
    rocm-version: "0.0"
  - os-distro: "opensuse"
    os-version: "15.5"
    rocm-version: "6.3"
  # opensuse 15.6
  - os-distro: "opensuse"
    os-version: "15.6"
    rocm-version: "0.0"
  - os-distro: "opensuse"
    os-version: "15.6"
    rocm-version: "6.3"
  - os-distro: "opensuse"
    os-version: "15.6"
    rocm-version: "6.4"
  - os-distro: "opensuse"
    os-version: "15.6"
    rocm-version: "7.0"
  # RHEL 8.10
  - os-distro: "rhel"
    os-version: "8.10"
    rocm-version: "0.0"
  - os-distro: "rhel"
    os-version: "8.10"
    rocm-version: "6.3"
  - os-distro: "rhel"
    os-version: "8.10"
    rocm-version: "6.4"
  - os-distro: "rhel"
    os-version: "8.10"
    rocm-version: "7.0"
  # RHEL 9.4
  - os-distro: "rhel"
    os-version: "9.4"
    rocm-version: "0.0"
  - os-distro: "rhel"
    os-version: "9.4"
    rocm-version: "6.3"
  - os-distro: "rhel"
    os-version: "9.4"
    rocm-version: "6.4"
  - os-distro: "rhel"
    os-version: "9.4"
    rocm-version: "7.0"
  # RHEL 9.5
  - os-distro: "rhel"
    os-version: "9.5"
    rocm-version: "0.0"
  - os-distro: "rhel"
    os-version: "9.5"
    rocm-version: "6.3"
  - os-distro: "rhel"
    os-version: "9.5"
    rocm-version: "6.4"
  - os-distro: "rhel"
    os-version: "9.5"
    rocm-version: "7.0"
